 // Source code is unavailable, and was generated by the Fernflower decompiler.

public class newstrings {

    public static void main(String[] var0) {
        String var1 = "Hello 'world' '   ";
        // System.out.println(var1.toUpperCase());
        // System.out.println(var1.toLowerCase());
        System.out.println(var1.startsWith("H"));
        // System.out.println(var1.endsWith("S"));
        // System.out.println(var1.replace("o", "O"));
        // System.out.println(var1.length());
        // System.out.println(var1.trim());
        // System.out.println(var1);
    }
}
