 // Source code is unavailable, and was generated by the Fernflower decompiler.

import java.util.Date;

public class news {

    public static void main(String[] var0) {
        System.out.println("hello world ");
        byte var1 = 45;
        System.out.println(var1);
        long var2 = 7898999998483404804L;
        System.out.println(var2);
        float var4 = 56.89F;
        System.out.println(var4);
        char var5 = 'A';
        boolean var6 = false;
        System.out.println(var6);
        System.out.println(var5);
        Date var7 = new Date();
        System.out.println(var7);
    }
}
